### ISSUE TITLE
File size issues, iOS 14.3 fix

### ISSUE THREAD

**Issue by Kaspik** [pixelmatrix/iOS14-HDR-Export-Bug#1]
Thanks for this repo, it was really helpful when debugging this issue! Any other preset than medium that would work results in much bigger files - even 1280px results even in 10x bigger file (when resampling 4H 60FPS HDR HEVC video).

Seems like iOS 14.3 released on Dec 14th 2020 fixed this issue - at least with `medium` quality - so we don't have to implement workarounds but ask users to update their iOS versions. 🎉

**Comment by pixelmatrix** [comment]
So glad to hear it was useful for others! I needed it to repro for Apple, but also to try to find a workaround for my company. That's fantastic news about the fix as well. I'll investigate today!
